### ISSUE TITLE
GSI not connected with CS 2

### ISSUE THREAD

**Issue by denrio157** [fyflo/CS2-CSGO-HUDS-Observer-fyflo#1]
Hello, i like and i try your program. HUD is good and normal, but with the radar map, I have some a little problem. I've followed all the notes and directions but still can't connect. Any suggestions?
![gsi](https://github.com/fyflo/CS2-CSGO-HUDS-Observer-fyflo/assets/31591836/65c0fc46-3e2a-47f4-9ba1-22d5270dc86e)

**Comment by fyflo** [comment]
1. Did you put all 4 files in the cfg folder?
2. Try to join the demo, and then launch the RUN_HOOD & RUN_RADAR servers

**Comment by denrio157** [comment]
> 1. Did you put all 4 files in the cfg folder?
> 2. Try to join the demo, and then launch the RUN_HOOD & RUN_RADAR servers

Of course, I followed all the steps given but it's still the same as that. Are there any steps missed?

**Comment by denrio157** [comment]
![image](https://github.com/fyflo/CS2-CSGO-HUDS-Observer-fyflo/assets/31591836/3d58bee9-a9bc-479c-acda-7f8ebc200ac4)

**Comment by fyflo** [comment]
Try to put this file in the folder with cfg cs 2
https://drive.google.com/file/d/1od0GxQHU6Md74EMK6eZL-r-zBW0__0Wp/view?usp=drive_link

**Comment by fyflo** [comment]
![image](https://github.com/fyflo/CS2-CSGO-HUDS-Observer-fyflo/assets/109218111/a83283ac-c065-4e05-ba65-9bdb6b68676b)

**Comment by denrio157** [comment]
Thank you somuch sir.. its working <3 
![image](https://github.com/fyflo/CS2-CSGO-HUDS-Observer-fyflo/assets/31591836/d5214517-bd68-47d4-bbd8-7daf299caf5f)
