### ISSUE TITLE
HUD cannot connect to CS2

### ISSUE THREAD

**Issue by AsukaO0** [fyflo/CS2-CSGO-HUDS-Observer-fyflo#4]
Hello, I overwrote the cfg file according to the location, but it cannot be linked to cs2. How to solve it?

**Comment by fyflo** [comment]
To answer this question, you need to clarify which `cfg` file. there is a speech.
And what was changed in it?

**Comment by AsukaO0** [comment]
I modified the APIkey in the config.jsons file and put observerspectator.cfg into the cfg folder of cs2 but hud cannot connect to cs2

**Comment by fyflo** [comment]
First: you don't need to change the `APIkey`.
Second: send the exact address where you placed the `gamestate_integration_observerspectator`. Since many people confuse the placement of cgf CS2 with the location of cfg CSGO

**Comment by AsukaO0** [comment]
I unzipped the file again
I placed the cfg file in Counter-Strike Global Offensive\ game \csgo\cfg\
Still can't connect to cs2.
 I have another hud used on csgo. I can connect using the same method, but the number of the player on the left will be displayed as 1、2、3、4、0.

**Comment by fyflo** [comment]
five minutes. I'll fix the file.
I found an error after updating the player locations.

**Comment by fyflo** [comment]
![2024-02-03 16_37_50-CSGO OVERLAY FOR CUSTOM HUD](https://github.com/fyflo/CS2-CSGO-HUDS-Observer-fyflo/assets/109218111/a6a0f59a-11b5-4ae5-ad83-cb2ef6ed233e)

Updated the file.
Download the application

**Comment by AsukaO0** [comment]
everything is fine now
Could you please tell me how to correct the wrong player number?

**Comment by fyflo** [comment]
What HUD are we talking about?

**Comment by AsukaO0** [comment]
The HUD I made before worked fine in csgo
But in CS2, the player HUD on the left shows 1, 2, 3, 4, 0
On the right are 5, 6, 7, 8, 9
Can you tell me where to change it correctly?

**Comment by fyflo** [comment]
You can send me to the mail Stream@gaprt.ru.
I will correct him and send it back to you.

**Comment by AsukaO0** [comment]
ok，thank you very much
