### ISSUE TITLE
Не показывает данные матча в основном худе

### ISSUE THREAD

**Issue by TsaplinIA** [fyflo/CS2-CSGO-HUDS-Observer-fyflo#5]
Всё сделал по инструкции из Readme.
Радар работает корректно(из чего я делаю выводы что gsi работает корректно)
Однако в основном худе всегда счёт 10:10, ников нет и т.д.
порты никакие не менял
В чём может быть проблема?

**Comment by fyflo** [comment]
> Всё сделал по инструкции из Readme. Радар работает корректно(из чего я делаю выводы что gsi работает корректно) Однако в основном худе всегда счёт 10:10, ников нет и т.д. порты никакие не менял В чём может быть проблема?

Несколько вариантов.
1. Не закинули файл cfg
2. Вы заходите не на кств или демку

Пришлите скриншоты где разместили файлы и т.д.

**Comment by TsaplinIA** [comment]
Проблема была на стороне сети, поменял порт с 1337 на 60000, всё завелось
