### ISSUE TITLE
Request for Updated Weapon SVG Icons

### ISSUE THREAD

**Issue by EEnigma-Hub** [fyflo/CS2-CSGO-HUDS-Observer-fyflo#6]
Hello, first of all, thank you for sharing the project!

I looked at the SVG files in the [CS2-CSGO-HUDS-Observer-fyflo/public/files/img/weapons](https://github.com/fyflo/CS2-CSGO-HUDS-Observer-fyflo/tree/main/public/files/img/weapons) directory, and I need these weapon icons. However, I noticed that some of the SVG files are outdated. Specifically, some weapon icons appear to be old.

Is there a chance you could add updated SVG files for these icons? Or do you have any idea how I can access these SVG files?

Thank you!

**Comment by fyflo** [comment]
Good afternoon! 

1. In this section of the index file.js in the folder of the selected hud, change the file extension from png to svg: 


```
$bottom
 .find("#player_weapon_secondary_img")
 .attr("src", "/files/img/weapons/" + name + ".`png`")
 .addClass("invert")
 .addClass(view);
 } else {
 $top
 .find("#player_weapon_primary_img")
 .attr("src", "/files/img/weapons/" + name + ".`png`")
 .addClass("invert")
 .addClass(view);
 }
 }
 }
 if (type == "C4") {
 view = weapon.state == "active" ? "player_bomb_selected" : "player_bomb";
 $bottom.find("#player_bomb_kit_image").addClass(view);
 }
 if (!checkGuns(weapons)) {
 view += side.substr(8) == "right" ? " img-hor" : "";
 $top
.find("#player_weapon_primary_img")
.attr("src", "/files/img/weapons/" + name + ".`png`")
.addClass("invert")
.addClass(view); 
```


2. Add new files with the svg extension to the folder with the image of the weapon 

3. To make svg from png, you can use the online image convector.
